[coverage:run]
relative_files = True
[pytest]
testpaths = src/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov=src/00_Data_Clean --cov=src/02_Lineal_Regression --cov=src/03_Random_Forest --cov=src/04_Model_Evaluation --cov=src/05_Regularization --cov=src/Common_Functions --cov-report=xml:coverage.xml --cov-report=term-missing